In [13]:
import numpy

In [3]:
array1 = numpy.array([2,3,5,6,11,13,17,18,23,29,31])
print(array1) #->[2,3,5,6,11,13,17,18,23,29,31]

[ 2  3  5  6 11 13 17 18 23 29 31]


In [4]:
#균일한 값으로 생성 numpy.full(n, number) number의 수를 n번 반복해서 리스트로 만들어줌
array2 = numpy.full(6, 7) 
print(array2) #-> [7 7 7 7 7 7 7]

[7 7 7 7 7 7]


In [10]:
array3 = numpy.full(6, 0)
array4 = numpy.zeros(6, dtype=int) #numpy.zeros(number, dtype=변수형)

print(array3)
print(array4)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


In [12]:
array5 = numpy.full(6, 1)
array6 = numpy.ones(6, dtype=int) #numpy.ones(n, dtype =변수형)
print(array5)
print(array6)


[1 1 1 1 1 1]
[1 1 1 1 1 1]


In [14]:
array7 = numpy.random.random(6) #numpy 내의 random 모듈이 존재함
array8 = numpy.random.random(6) #0부터 1사이의 값 6개 랜덤으로 출력

print(array7)
print(array8)

[0.282074   0.68584324 0.26212714 0.46282163 0.14789287 0.89925643]
[0.75080915 0.4464631  0.80897227 0.76095333 0.03465991 0.89162435]


In [15]:
#연속된 값들이 담긴 numpy array 생성 
array9 = numpy.arange(6)
print(array9) #-> [0 1 2 3 4 5]

[0 1 2 3 4 5]


In [17]:
array10 = numpy.arange(2, 7) # 2~6까지의 정수를 리스트로 출력
print(array10) #-> [2 3 4 5 6]

[2 3 4 5 6]


In [18]:
array11 = numpy.arange(3, 17 , 3) # 3~16까지의 정수 중 3간격으로 된 수를 출력
print(array11) #-> [3 6 9 12 15]

[ 3  6  9 12 15]
