In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17 ,19 ,23 , 29, 31])

In [3]:
array1[0]

2

In [4]:
array1[2]

5

In [5]:
array1[-1]

31

In [6]:
#리스트 인덱스 슬라이싱 처리 가능

In [8]:
array1[[1, 3, 4]] #변수[[index1, index2 , ~~~]] 

array([ 3,  7, 11])

In [11]:
array2 = np.array([2, 1, 3]) 
array2

array([2, 1, 3])

In [12]:
array1[array2] # = array1[[2, 1, 3]] 이랑 같다

array([5, 3, 7])

In [13]:
array1[2:7] # index 2부터 6까지 출력
array1[:7] # index 0부터 6까지 출력
array1[2:] # index 2부터 끝까지 출력
array1[2:11:2] #index 2부터 2의 배수 수만 출력 2,4,6,8,10 index만

array([ 5, 11, 17, 23, 31])