In [1]:
import numpy as np

In [3]:
array1 = np.arange(10)
array2 = np.arange(10,20) 

In [4]:
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
# array1의 값을 2씩 곱하기
array1 * 2
# array1의 값을 2로 나누기
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
array1 #-> 원래대로 남아있음!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array1 = array1 * 2 
print(array1)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
array1 = np.arange(10)
array2 = np.arange(10,20) 

In [10]:
#같은 index끼리 더하기
array1 + array2 
#같은 index끼리 뺴기
array1 - array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
#같은 index끼리 곱하기
array1 * array2
#같은 index끼리 나누기
array1 / array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])